INSERT into MENU values (1, 'Kimchi', '김치');
INSERT into MENU values (2, 'Milk', '우유');
INSERT into MENU values (3, 'Bulgogi', '쇠고기불고기');
INSERT into MENU values (4, 'Stir-fried Pork', '제육볶음');
INSERT into MENU values (5, 'Fish Cake Soup', '어묵국');
INSERT into MENU values (6, 'Fried Egg', '계란후라이');
INSERT into MENU values (7, 'Cabbage And Shank Bone Soup', '사골우거지국');
INSERT into MENU values (8, 'Seasoned Chamnamul', '참나물생무침');
INSERT into MENU values (9, 'Lotus Root In Soy Sauce', '연근조림');
INSERT into MENU values (10, 'Cereal', '씨리얼');
INSERT into MENU values (11, 'Bread And Jam', '식빵과 쨈');
INSERT into MENU values (12, 'Brownie', '브라우니');
INSERT into MENU values (13, 'Bena Sprout Soup', '매운콩나물국');
INSERT into MENU values (14, 'Braised Mackerel', '고등어무조림');
INSERT into MENU values (15, 'Cabage Salad', '새싹샐러드');
INSERT into MENU values (16, 'Acorn Jelly In Sauce', '도토리묵무침');
INSERT into MENU values (17, 'Sauteed Seaweed', '미역줄기볶음');
INSERT into MENU values (18, 'Millet Rice', '기장밥');
INSERT into MENU values (19, 'Steamed Soft Bean Curd', '연두부찜');
INSERT into MENU values (20, 'Veges Seasoned', '건강야채무침');
INSERT into MENU values (21, 'Rice', '쌀밥');
INSERT into MENU values (22, 'Sliced Rice Cake Soup', '매생이떡국');
INSERT into MENU values (23, 'Spicy Stir-fried Chicken', '뼈없는닭갈비');
INSERT into MENU values (24, 'Udon Soup', '우동국물');
INSERT into MENU values (25, 'Honey Pan Cake', '꿀호떡');
INSERT into MENU values (26, 'Soybean Paste Soup with Dried Radish Leaves', '시래기된장국');
INSERT into MENU values (27, 'Stir-fried Korean Sausage', '순대볶음');
INSERT into MENU values (28, 'Seasoned Cucumber and Chives', '오이부추무침');
INSERT into MENU values (29, 'Rice with Mushroom', '버섯영양밥');
INSERT into MENU values (30, 'Beef Bon Soup', '사골국');
INSERT into MENU values (31, 'Chicken Nugget', '치킨너겟');
INSERT into MENU values (32, 'Seasoned Young Summer Radish with Soybean Paste', '열무나물');
INSERT into MENU values (33, 'Seasoned Red Pepper', '고추지');
INSERT into MENU values (34, 'Yogurt', '요구르트');
INSERT into MENU values (35, 'Fried Rice With Beef', '쇠고기볶음밥');
INSERT into MENU values (36, 'Deep-fried Glass Noodles in Seaweed', '김말이튀김');
INSERT into MENU values (37, 'Seasoned Pickled Radish and Chives', '단무지부추무침');
INSERT into MENU values (38, 'Stir-fried Fish Cake', '잡채어묵볶음');
INSERT into MENU values (39, 'Salted Burdock', '우엉조림');
INSERT into MENU values (40, 'Sausage Stew', '부대찌개');
INSERT into MENU values (41, 'not yet', '수육국밥');
-- INSERT into MENU values (1, 'Kimchi', 'FFFFFF', '김치');
-- INSERT into MENU values (2, 'Milk', 'FFFFFF', '우유');
-- INSERT into MENU values (3, 'Bulgogi', 'FFFFFF', '쇠고기불고기');
-- INSERT into MENU values (4, 'Stir-fried Pork', 'FFFFFF', '제육볶음');
-- INSERT into MENU values (5, 'Fish Cake Soup', 'FFFFFF', '어묵국');
-- INSERT into MENU values (6, 'Fried Egg', 'FFFFFF', '계란후라이');
-- INSERT into MENU values (7, 'Cabbage And Shank Bone Soup', 'FFFFFF', '사골우거지국');
-- INSERT into MENU values (8, 'Seasoned Chamnamul', 'FFFFFF', '참나물생무침');
-- INSERT into MENU values (9, 'Lotus Root In Soy Sauce', 'FFFFFF', '연근조림');
-- INSERT into MENU values (10, 'Cereal', 'FFFFFF', '씨리얼');
-- INSERT into MENU values (11, 'Bread And Jam', 'FFFFFF', '식빵과 쨈');
-- INSERT into MENU values (12, 'Brownie', 'FFFFFF', '브라우니');
-- INSERT into MENU values (13, 'Bena Sprout Soup', 'FFFFFF', '매운콩나물국');
-- INSERT into MENU values (14, 'Braised Mackerel', 'FFFFFF', '고등어무조림');
-- INSERT into MENU values (15, 'Cabage Salad', 'FFFFFF', '새싹샐러드');
-- INSERT into MENU values (16, 'Acorn Jelly In Sauce', 'FFFFFF', '도토리묵무침');
-- INSERT into MENU values (17, 'Sauteed Seaweed', 'FFFFFF', '미역줄기볶음');
-- INSERT into MENU values (18, 'Millet Rice', 'FFFFFF', '기장밥');
-- INSERT into MENU values (19, 'Steamed Soft Bean Curd', 'FFFFFF', '연두부찜');
-- INSERT into MENU values (20, 'Veges Seasoned', 'FFFFFF', '건강야채무침');
-- INSERT into MENU values (21, 'Rice', 'FFFFFF', '쌀밥');
-- INSERT into MENU values (22, 'Sliced Rice Cake Soup', 'FFFFFF', '매생이떡국');
-- INSERT into MENU values (23, 'Spicy Stir-fried Chicken', 'FFFFFF', '뼈없는닭갈비');
-- INSERT into MENU values (24, 'Udon Soup', 'FFFFFF', '우동국물');
-- INSERT into MENU values (25, 'Honey Pan Cake', 'FFFFFF', '꿀호떡');
-- INSERT into MENU values (26, 'Soybean Paste Soup with Dried Radish Leaves', 'FFFFFF', '시래기된장국');
-- INSERT into MENU values (27, 'Stir-fried Korean Sausage', 'FFFFFF', '순대볶음');
-- INSERT into MENU values (28, 'Seasoned Cucumber and Chives', 'FFFFFF', '오이부추무침');
-- INSERT into MENU values (29, 'Rice with Mushroom', 'FFFFFF', '버섯영양밥');
-- INSERT into MENU values (30, 'Beef Bon Soup', 'FFFFFF', '사골국');
-- INSERT into MENU values (31, 'Chicken Nugget', 'FFFFFF', '치킨너겟');
-- INSERT into MENU values (32, 'Seasoned Young Summer Radish with Soybean Paste', 'FFFFFF', '열무나물');
-- INSERT into MENU values (33, 'Seasoned Red Pepper', 'FFFFFF', '고추지');
-- INSERT into MENU values (34, 'Yogurt', 'FFFFFF', '요구르트');
-- INSERT into MENU values (35, 'Fried Rice With Beef', 'FFFFFF', '쇠고기볶음밥');
-- INSERT into MENU values (36, 'Deep-fried Glass Noodles in Seaweed', 'FFFFFF', '김말이튀김');
-- INSERT into MENU values (37, 'Seasoned Pickled Radish and Chives', 'FFFFFF', '단무지부추무침');
-- INSERT into MENU values (38, 'Stir-fried Fish Cake', 'FFFFFF', '잡채어묵볶음');
-- INSERT into MENU values (39, 'Salted Burdock', 'FFFFFF', '우엉조림');
-- INSERT into MENU values (40, 'Sausage Stew', 'FFFFFF', '부대찌개');
-- INSERT into MENU values (41, 'Rice', 'FFFFFF', '쌀밥');
-- INSERT into MENU values (42, 'Rice', 'FFFFFF', '쌀밥');
-- INSERT into MENU values (43, 'Rice', 'FFFFFF', '쌀밥');
-- INSERT into MENU values (44, 'Rice', 'FFFFFF', '쌀밥');
-- INSERT into MENU values (45, 'Rice', 'FFFFFF', '쌀밥');
-- INSERT into MENU values (46, 'Rice', 'FFFFFF', '쌀밥');
-- INSERT into MENU values (47, 'Rice', 'FFFFFF', '쌀밥');
-- INSERT into MENU values (48, 'Rice', 'FFFFFF', '쌀밥');
-- INSERT into MENU values (49, 'Rice', 'FFFFFF', '쌀밥');
-- INSERT into MENU values (50, 'Rice', 'FFFFFF', '쌀밥');
-- INSERT into MENU values (51, 'Rice', 'FFFFFF', '쌀밥');
-- INSERT into MENU values (52, 'Rice', 'FFFFFF', '쌀밥');
-- INSERT into MENU values (53, 'Rice', 'FFFFFF', '쌀밥');
-- INSERT into MENU values (54, 'Rice', 'FFFFFF', '쌀밥');
-- INSERT into MENU values (55, 'Rice', 'FFFFFF', '쌀밥');
-- INSERT into MENU values (56, 'Rice', 'FFFFFF', '쌀밥');
-- INSERT into MENU values (57, 'Rice', 'FFFFFF', '쌀밥');
-- INSERT into MENU values (58, 'Rice', 'FFFFFF', '쌀밥');
-- INSERT into MENU values (59, 'Rice', 'FFFFFF', '쌀밥');
-- INSERT into MENU values (60, 'Rice', 'FFFFFF', '쌀밥');
-- INSERT into MENU values (61, 'Rice', 'FFFFFF', '쌀밥');
-- INSERT into MENU values (62, 'Rice', 'FFFFFF', '쌀밥');
-- INSERT into MENU values (63, 'Rice', 'FFFFFF', '쌀밥');
-- INSERT into MENU values (64, 'Rice', 'FFFFFF', '쌀밥');
-- INSERT into MENU values (65, 'Rice', 'FFFFFF', '쌀밥');
-- INSERT into MENU values (66, 'Rice', 'FFFFFF', '쌀밥');
-- INSERT into MENU values (67, 'Rice', 'FFFFFF', '쌀밥');
-- INSERT into MENU values (68, 'Rice', 'FFFFFF', '쌀밥');
-- INSERT into MENU values (69, 'Rice', 'FFFFFF', '쌀밥');
-- INSERT into MENU values (70, 'Rice', 'FFFFFF', '쌀밥');
-- INSERT into MENU values (71, 'Rice', 'FFFFFF', '쌀밥');
-- INSERT into MENU values (72, 'Rice', 'FFFFFF', '쌀밥');
-- INSERT into MENU values (73, 'Rice', 'FFFFFF', '쌀밥');
-- INSERT into MENU values (74, 'Rice', 'FFFFFF', '쌀밥');
-- INSERT into MENU values (75, 'Rice', 'FFFFFF', '쌀밥');
-- INSERT into MENU values (76, 'Rice', 'FFFFFF', '쌀밥');
-- INSERT into MENU values (77, 'Rice', 'FFFFFF', '쌀밥');
-- INSERT into MENU values (78, 'Rice', 'FFFFFF', '쌀밥');
-- INSERT into MENU values (79, 'Rice', 'FFFFFF', '쌀밥');
-- INSERT into MENU values (80, 'Rice', 'FFFFFF', '쌀밥');
-- INSERT into MENU values (81, 'Rice', 'FFFFFF', '쌀밥');
-- INSERT into MENU values (82, 'Rice', 'FFFFFF', '쌀밥');
-- INSERT into MENU values (83, 'Rice', 'FFFFFF', '쌀밥');
-- INSERT into MENU values (84, 'Rice', 'FFFFFF', '쌀밥');
-- INSERT into MENU values (85, 'Rice', 'FFFFFF', '쌀밥');
-- INSERT into MENU values (86, 'Rice', 'FFFFFF', '쌀밥');
-- INSERT into MENU values (87, 'Rice', 'FFFFFF', '쌀밥');
-- INSERT into MENU values (88, 'Rice', 'FFFFFF', '쌀밥');
-- INSERT into MENU values (89, 'Rice', 'FFFFFF', '쌀밥');
-- INSERT into MENU values (90, 'Rice', 'FFFFFF', '쌀밥');
-- INSERT into MENU values (91, 'Rice', 'FFFFFF', '쌀밥');
-- INSERT into MENU values (92, 'Rice', 'FFFFFF', '쌀밥');
-- INSERT into MENU values (93, 'Rice', 'FFFFFF', '쌀밥');
-- INSERT into MENU values (94, 'Rice', 'FFFFFF', '쌀밥');
-- INSERT into MENU values (95, 'Rice', 'FFFFFF', '쌀밥');
-- INSERT into MENU values (96, 'Rice', 'FFFFFF', '쌀밥');
-- INSERT into MENU values (97, 'Rice', 'FFFFFF', '쌀밥');
-- INSERT into MENU values (98, 'Rice', 'FFFFFF', '쌀밥');
-- INSERT into MENU values (99, 'Rice', 'FFFFFF', '쌀밥');
-- INSERT into MENU values (100, 'Rice', 'FFFFFF', '쌀밥');
-- INSERT into MENU values (101, 'Rice', 'FFFFFF', '쌀밥');
-- INSERT into MENU values (102, 'Rice', 'FFFFFF', '쌀밥');
-- INSERT into MENU values (103, 'Rice', 'FFFFFF', '쌀밥');
-- INSERT into MENU values (104, 'Rice', 'FFFFFF', '쌀밥');
-- INSERT into MENU values (105, 'Rice', 'FFFFFF', '쌀밥');
-- INSERT into MENU values (106, 'Rice', 'FFFFFF', '쌀밥');
-- INSERT into MENU values (107, 'Rice', 'FFFFFF', '쌀밥');
-- INSERT into MENU values (108, 'Rice', 'FFFFFF', '쌀밥');
-- INSERT into MENU values (109, 'Rice', 'FFFFFF', '쌀밥');
-- INSERT into MENU values (110, 'Rice', 'FFFFFF', '쌀밥');
-- INSERT into MENU values (111, 'Rice', 'FFFFFF', '쌀밥');
-- INSERT into MENU values (112, 'Rice', 'FFFFFF', '쌀밥');
-- INSERT into MENU values (113, 'Rice', 'FFFFFF', '쌀밥');
-- INSERT into MENU values (114, 'Rice', 'FFFFFF', '쌀밥');
-- INSERT into MENU values (115, 'Rice', 'FFFFFF', '쌀밥');
-- INSERT into MENU values (116, 'Rice', 'FFFFFF', '쌀밥');
-- INSERT into MENU values (117, 'Rice', 'FFFFFF', '쌀밥');
-- INSERT into MENU values (118, 'Rice', 'FFFFFF', '쌀밥');
-- INSERT into MENU values (119, 'Rice', 'FFFFFF', '쌀밥');
-- INSERT into MENU values (120, 'Rice', 'FFFFFF', '쌀밥');
-- INSERT into MENU values (121, 'Rice', 'FFFFFF', '쌀밥');