INSERT into MENU values (1, 'Kimchi', 'FFFFFF', '김치');
INSERT into MENU values (2, 'Milk', 'FFFFFF', '우유');
INSERT into MENU values (3, 'Bulgogi', 'FFFFFF', '쇠고기불고기');
INSERT into MENU values (4, 'Stir-fried Pork', 'FFFFFF', '제육볶음');
INSERT into MENU values (5, 'Fish Cake Soup', 'FFFFFF', '어묵국');
INSERT into MENU values (6, 'Fried Egg', 'FFFFFF', '계란후라이');
INSERT into MENU values (7, 'Cabbage And Shank Bone Soup', 'FFFFFF', '사골우거지국');
INSERT into MENU values (8, 'Seasoned Chamnamul', 'FFFFFF', '참나물생무침');
INSERT into MENU values (9, 'Lotus Root In Soy Sauce', 'FFFFFF', '연근조림');
INSERT into MENU values (10, 'Cereal', 'FFFFFF', '씨리얼');
INSERT into MENU values (11, 'Bread And Jam', 'FFFFFF', '식빵과 쨈');
INSERT into MENU values (12, 'Brownie', 'FFFFFF', '브라우니');
INSERT into MENU values (13, 'Bena Sprout Soup', 'FFFFFF', '매운콩나물국');
INSERT into MENU values (14, 'Braised Mackerel', 'FFFFFF', '고등어무조림');
INSERT into MENU values (15, 'Cabage Salad', 'FFFFFF', '새싹샐러드');
INSERT into MENU values (16, 'Acorn Jelly In Sauce', 'FFFFFF', '도토리묵무침');
INSERT into MENU values (17, 'Sauteed Seaweed', 'FFFFFF', '미역줄기볶음');
INSERT into MENU values (18, 'Millet Rice', 'FFFFFF', '기장밥');
INSERT into MENU values (19, 'Steamed Soft Bean Curd', 'FFFFFF', '연두부찜');
INSERT into MENU values (20, 'Veges Seasoned', 'FFFFFF', '건강야채무침');
INSERT into MENU values (21, 'Rice', 'FFFFFF', '쌀밥');